version: '3.1'
services:
    api:
        image:yassineabidar/flex-backend
        build: 
            dockerfile: dockerfile
            context: .
        depends_on: 
            -mysql
        environment: 
            DATABASE_URL:mysql//
            NODE_ENV:development
            PORT:3000
        ports: 
            -"8080:3000"
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        
  